name: pr-auto
on:
  pull_request:
    types: [opened]

jobs:
  pull-request-tools:
    runs-on: ubuntu-latest
    steps:
    - name: step1 
      run: echo hello world
    - name: step2
      run: |
        echo hi1
        echo hi2
